### PR TITLE
Try third-party markdown checker

### LINKED ISSUE #2197: Add broken MD links check to GH actions
See https://github.com/gaurav-nelson/github-action-markdown-link-check.

Should be particularly useful for deployments.

### PR DESCRIPTION
**Pull request by EndymionJkb**
# Description

Trying the third-party tool, retaining only the artifact check. Variation of #2246.

## Type of change

- [ ] Bug fix 
- [X] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [ ] Documentation or wording changes
- [ ] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes - (well, only one small fix. Rest fixed in previous PRs)
- [X] Complex code has been commented, including external interfaces
- [N/A] Tests are included for all code paths
- [X] The base branch is either `master`, or there's a description of how to merge

## Issue Resolution

Closes #2197

### CODE REVIEW

File: pkg/deployments/src/artifact.ts [hunk 1]
```diff
@@ -58,6 +74,28 @@ export function checkArtifact(task: Task): void {
...
+
+  for (const line of readmeLines) {
+    // Tolerate differences in case (e.g., veBoost vs VeBoost).
+    if (line.toLowerCase() == expectedContent.toLowerCase()) {
+      found = true;
+      break;
+    }
+  }
+
+  if (found) {
```
Comment (jubeira) [inline pkg/deployments/src/artifact.ts:92]:
```suggestion
  const linkFound = readmeLines.find((line) => line.toLowerCase() == expectedContent.toLowerCase()) !== undefined;

  if (linkFound) {
```

Slightly more compact version

File: pkg/deployments/src/artifact.ts [hunk 2]
```diff
@@ -37,6 +38,15 @@ function _extractArtifact(task: Task, file: string, contract?: string) {
...
  */
 export function checkArtifact(task: Task): void {
+  let readmeLines: string[] = [];
+
+  const filePath = path.join(task.dir(), `readme.md`);
+  const readmeFileExists = fs.existsSync(filePath) && fs.statSync(filePath).isFile();
+  if (readmeFileExists) {
+    const readmeContents = fs.readFileSync(filePath).toString();
+    readmeLines = readmeContents.split('\n');
+  }
```
Comment (jubeira) [inline pkg/deployments/src/artifact.ts:48]: I think you could also do this inside `checkReadmeArtifactLink`, since you only need the `readmeLines` inside there, and you are already doing `if (readmeFileExists)` below. 

Instead of sending the lines, you'd send the file path, which is also available.

**Review by jubeira — COMMENTED** [review]
I think this makes sense and it'll help a lot.

I've left two minor improvement suggestions; otherwise looks good.

Some more thoughts:
- I think we should also modify the templates for the deployment preparation / deployment. If we add the expected output links in the preparation stage, won't the CI fail with this? 
- [Not for this PR] Eventually it'd be good to have an automated check that verifies which artifacts should be present (e.g. for a pool deployment, there should be one for the pool and one for the factory at the very least, which is something we don't enforce today).

File: pkg/deployments/src/artifact.ts (hunk 2 above)
Comment (EndymionJkb) [reply pkg/deployments/src/artifact.ts:48]: That's an optimization so that I don't have to read the file (a slow operation) more than once. Usually there's only one artifact, so it doesn't make much difference, but if there are three or four (happens sometimes), it would read the file multiple times.

**Comment by EndymionJkb** [comment]
> Some more thoughts:
> 
> * I think we should also modify the templates for the deployment preparation / deployment. If we add the expected output links in the preparation stage, won't the CI fail with this?

Yes; we're hitting exactly this case with the recent Yearn deployment lol. Thanks, good catch!

**Review by jubeira — APPROVED** [review]
:rocket:
